### POST Register
POST http://localhost:8090/api/user/register
Content-Type: application/json

{
  "login": "test1",
  "password": "pass1"
}

### POST Login
POST http://localhost:8090/api/user/login
Content-Type: application/json

{
  "login": "test1",
  "password": "pass1"
}

### POST Register order
POST http://localhost:8090/api/user/orders
Content-Type: text/plain

9278923470

### GET All registered orders
GET http://localhost:8090/api/user/orders

### GET Balance
GET http://localhost:8090/api/user/balance

### POST Withdraw
POST http://localhost:8090//api/user/balance/withdraw
Content-Type: application/json

{
  "order": "744482",
  "sum": 20.23
}

### GET Withdrawals
GET http://localhost:8090/api/user/withdrawals